# Generated by Django 6.0.4 on 2026-05-07 16:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='USD credited to every new user on signup. Set to 0 to disable.', max_digits=8)),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Balance falls below this → yellow warning indicator in the UI.', max_digits=8)),
                ('critical_threshold', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Balance falls below this → red critical indicator in the UI.', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing Settings',
                'verbose_name_plural': 'Billing Settings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified.', verbose_name='modified at')),
                ('deleted', models.BooleanField(default=False, help_text='Set to False when an element is deleted')),
                ('name', models.CharField(max_length=100)),
                ('operation_type', models.CharField(choices=[('generic', 'Generic Operation')], max_length=50, unique=True)),
                ('markup', models.DecimalField(decimal_places=4, default=Decimal('1.0'), help_text='Multiplier applied on top of the base cost (1.0 = no markup)', max_digits=6)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=6, help_text='Fixed price per unit in USD (optional; use for flat-rate billing)', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cost Template',
                'verbose_name_plural': 'Cost Templates',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified.', verbose_name='modified at')),
                ('deleted', models.BooleanField(default=False, help_text='Set to False when an element is deleted')),
                ('balance', models.DecimalField(decimal_places=6, default=0, help_text='Current USD credit balance', max_digits=12)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0, help_text='Total USD deposited over lifetime', max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=6, default=0, help_text='Total USD spent over lifetime', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Balance',
                'verbose_name_plural': 'Credit Balances',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, help_text='Positive = credit added, negative = credit deducted', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=6, help_text="User's balance after this transaction", max_digits=12)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('admin_grant', 'Admin Grant'), ('execution_deduction', 'Execution Deduction'), ('chat_deduction', 'Chat Deduction'), ('refund', 'Refund')], max_length=30)),
                ('reference_id', models.CharField(blank=True, default='', help_text='Optional external reference (e.g. execution ID, order ID)', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', help_text='Used for idempotency on webhook processing', max_length=255)),
                ('context_type', models.CharField(blank=True, default='', help_text='Optional label for the entity that triggered this transaction', max_length=50)),
                ('context_id', models.PositiveIntegerField(blank=True, help_text='Optional PK of the entity that triggered this transaction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-created_at'], name='pm_billing__user_id_39d832_idx'), models.Index(fields=['transaction_type'], name='pm_billing__transac_994705_idx'), models.Index(fields=['stripe_payment_intent_id'], name='pm_billing__stripe__c451c1_idx'), models.Index(fields=['stripe_checkout_session_id'], name='pm_billing__stripe__a1277b_idx'), models.Index(fields=['context_type', 'context_id'], name='pm_billing__context_f3d273_idx')],
            },
        ),
    ]
